name: Actions Android Prod 😎
on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    environment: production
    # This stops builds that are in-progress once a new commit comes in
    concurrency: 
      group: unity-build-android
      cancel-in-progress: true
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
      - uses: actions/upload-artifact@v4
        with:
          name: build-Android
          path: build/Android
      
  deploy:
    name: Butler Push to Itch
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-Android
          path: build/Android
      # Upload to Itch
      - name: Butler Push
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: android
          ITCH_GAME: ${{vars.ITCHIO_PAGE}}
          ITCH_USER: peryloth
          PACKAGE: build/Android
      - name: Cleanup to avoid storage limit
        if: always()
        uses: geekyeggo/delete-artifact@v1
        with:
            name: build-Windows
